### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by dalb8** [jinhkim/ObjView#1]
Using the second latest commit d2566 there is this error:

```
Compiling 39 source files to /home/gerry/build/com.ubertome.objview/bin/classes
    [javac] /home/gerry/fdroiddata/build/com.ubertome.objview/src/com/ubertome/modelviewer/RendererGL.java:10: error: cannot find symbol
    [javac] import com.ubertome.modelviewer.R;
```

p.s any chance of using a FOSS licence and tags?

**Comment by jinhkim** [comment]
Hi, 

Are you sure you set up your Android environment correctly? And no, I'm not planning on using any open source licenses at the moment. But if you follow my project, you'll be notified of any changes.

**Comment by dalb8** [comment]
I'm pretty sure it's set up OK. I've built about 50 apps in the last two days. I deleted gen/ first though.

**Comment by jinhkim** [comment]
Ah, I just noticed the modelviewer/ folder was there. Please try cloning the latest commit! In the second last commit, I changed the project and package name to ObjView (and thus the directories) but the old directories remained. That's why I had 2 source folders and 2 gen folders (modelviewer/ and objview/). This is obviously not ideal so I removed the old directories in the latest commit.

**Comment by dalb8** [comment]
I was already using the second last commit.

**Comment by jinhkim** [comment]
Yes that's why I said you should use the LATEST commit. I tried cloning and building the latest commit and it worked fine for me.

**Comment by dalb8** [comment]
Sorry. It's working fine with last commit.
